RemoteCaptury
ihmcrobotics/ihmc-open-robotics-software pull request #327
Opened 2024-08-01 13:53 UTC by EAOZONE

Controls kinematicsStreaming and new UI button to start up remote Captury

2024-08-01 19:18 UTC, ds58 requested changes

2024-08-01 19:18 UTC, ds58 commented on ihmc-graphics/src/libgdx/java/us/ihmc/rdx/ui/remoteCaptury/RDXCapturyManager.java
Remove the `imgui.internal` from everywhere

2024-08-01 19:18 UTC, ds58 commented on ihmc-graphics/src/libgdx/java/us/ihmc/rdx/ui/remoteCaptury/RDXCapturyManager.java
Can you run a formatter to clean up the spaces and line breaks?

2024-08-01 19:18 UTC, ds58 commented on ihmc-graphics/src/libgdx/java/us/ihmc/rdx/ui/remoteCaptury/RDXCapturyManager.java
> +            RDXBaseUI.pushNotification("Hidding Fingers...");
Typo in "Hiding"

2024-08-01 19:18 UTC, ds58 commented on ihmc-graphics/src/libgdx/java/us/ihmc/rdx/ui/remoteCaptury/RDXCapturyManager.java
> +            RDXBaseUI.pushNotification("Hidding All Frames...");
Typo in "Hiding"

2024-08-01 19:18 UTC, ds58 commented on ihmc-graphics/src/libgdx/java/us/ihmc/rdx/ui/remoteCaptury/RDXCapturyManager.java
> +         imgui.internal.ImGui.setTooltip("Be ready to connect to Captury Live before turning on.");
maybe if you're not connected you should grey/disable these menu items?

2024-08-01 19:18 UTC, ds58 commented on ihmc-graphics/src/libgdx/java/us/ihmc/rdx/ui/remoteCaptury/RDXCapturyManager.java
> +   public boolean checkContain(int Actor_ID)
`Actor_ID` -> `actorID`

2024-08-01 20:04 UTC, calvertdw requested changes

2024-08-01 20:04 UTC, calvertdw commented on ihmc-graphics/src/libgdx/java/us/ihmc/rdx/ui/RDXBaseUI.java
> +   private final RDXCapturyManager capturyManager = new RDXCapturyManager();
This should not go in RDXBaseUI. Instead, RDXCapturyManager should get added to whatever RDX app you need it in.

2024-08-01 20:04 UTC, calvertdw commented on ihmc-avatar-interfaces/src/main/java/us/ihmc/avatar/networkProcessor/kinematicsToolboxModule/HumanoidKinematicsToolboxController.java
> +         listOfControllableRigidBodies.add(desiredFullRobotModel.getArmJoint(robotSide, ArmJointName.ELBOW_PITCH).getPredecessor());
What's the fix for this?

2024-08-01 20:04 UTC, calvertdw commented on ihmc-high-level-behaviors/src/libgdx/java/us/ihmc/rdx/ui/remoteCaptury/RDXCapturyKinematicsStreaming.java
> +      // ------------------------------------------------------------- End of Remove me
Are you removing this?

2024-08-01 20:04 UTC, calvertdw commented on ihmc-high-level-behaviors/src/libgdx/java/us/ihmc/rdx/ui/vr/RDXVRKinematicsStreamingMode.java
> +                                                             });
undo indents (using middle click drag to block select the space and hit the delete key is the easiest way to do that)

2024-08-01 20:04 UTC, calvertdw commented on ihmc-high-level-behaviors/src/libgdx/java/us/ihmc/rdx/ui/vr/RDXVRKinematicsStreamingMode.java
> +                                                                                 KinematicsToolboxRigidBodyMessage message = createRigidBodyMessage(controlledSegment,
undo indents (using middle click drag to block select the space and hit the delete key is the easiest way to do that)

2024-08-01 20:04 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/motionRetargeting/VRTrackedSegmentType.java
> +   CHEST("chest", null, 0.0, 10);
Might want to check with Luigi on this. Do we need two sets of parameters?

2024-08-02 15:09 UTC, EAOZONE commented on ihmc-avatar-interfaces/src/main/java/us/ihmc/avatar/networkProcessor/kinematicsToolboxModule/HumanoidKinematicsToolboxController.java
> +         listOfControllableRigidBodies.add(desiredFullRobotModel.getArmJoint(robotSide, ArmJointName.ELBOW_PITCH).getPredecessor());
Not sure, this is Sylvain stuff

2024-08-12 20:40 UTC, calvertdw approved these changes
Changes look good! Thanks!

2025-09-10 19:33 UTC, closed without merging