Add nvCOMP & Use Hybrid Depth Compression
ihmcrobotics/ihmc-open-robotics-software pull request #339
Opened 2024-08-12 20:55 UTC by TomaszTB

This PR adds tools for using nvCOMP. See any of the blow linked spread sheets for performance measurements. 

This PR also adds a lossless/lossy hybrid depth compression method. For 16 bit depth images, the hybrid method uses lossless compression (zstd) for the 8 most significant bits, and a lossy method (jpeg) for the 8 least significant bits. This way we can achieve high compression ratios while keeping artifacts to a low. 

| quality | compression ratio | spread sheet link |
|----|-------|-|
| 95 | 3.19  | [link](https://docs.google.com/spreadsheets/d/1JUXtFvnDTJuNvQhBU8uNALw481dmB9BwgtAUlpD_MrM/edit?usp=sharing) |
| 40 (current default) | 7.66  | [link](https://docs.google.com/spreadsheets/d/10q_v2c3G-CJauG3dQsCymbm5EcTZpqiX_lsMZwSTJH4/edit?usp=sharing) |
|  1 | 14.89 | [link](https://docs.google.com/spreadsheets/d/1RS3gWW5TfjlxEKG0rKz_iW17HMeF_R5IRUuM80Tm5SI/edit?usp=sharing) |

CUDA is required to decompress depth images compressed using this method, meaning that this PR introduces a CUDA requirement to the `RDXROS2ImageMessageVisualizer` (only for rendering depth images) and `RDXROS2ColoredPointCloudVisualizer`.

2024-08-12 21:10 UTC, ds58 requested changes

2024-08-12 21:10 UTC, ds58 commented on ihmc-high-level-behaviors/src/libgdx/java/us/ihmc/rdx/ui/graphics/ros2/RDXROS2ImageMessageVisualizer.java
> +                     LogTools.info("Creating Image Message Visualizer for {} with type DEPTH_HYBRID_16UC1", topic.getName());
I know you were just pattern matching here but can you do like

```
LogTools.info("Creating Image Message Visualizer for {} with type {}", topic.getName(), ImageMessageFormat.getFormat(imageMessage).name());
```

below the switch statement so you don't have to duplicate it for each case

2024-08-12 21:10 UTC, ds58 commented on ihmc-perception/src/main/java/us/ihmc/perception/demo/NVCompDemo.java
> +   protected static final String FILE_PATH = "/home/tbialek/Documents/ZED/ZED_ColorImage.png";
Remove hard coded absolute path

2024-08-12 21:10 UTC, ds58 commented on ihmc-perception/src/main/java/us/ihmc/perception/demo/NVCompDemo.java
> +   protected long compress(Mat image, BytePointer compressedImageData, PimplManager compressionManager)
Can this be removed in favor of the CUDACompressionTools class?

2024-08-12 21:10 UTC, ds58 commented on ihmc-perception/src/main/java/us/ihmc/perception/demo/NVCompDemo.java
> +   protected void decompressImage(BytePointer compressedHostBuffer, long compressedBufferSize, Mat matToPack)
Can this be removed in favor of the CUDACompressionTools class?

2024-08-12 21:31 UTC, calvertdw commented
Seeing this, it looks a little choppy. Would be better to see it on real robot data, however, I think the quality should be a little higher.
![image](https://github.com/user-attachments/assets/29d6925b-f5a9-4556-a834-267d0b67033c)

2024-08-12 21:42 UTC, ds58 commented
I think we should change the topics in this PR so it's like:
```
/ihmc/d455/image/depth/compressed
```

That way it's clear you probably shouldn't run perception algorithms on it.

2024-08-12 21:42 UTC, ds58 commented
> Seeing this, it looks a little choppy. Would be better to see it on real robot data, however, I think the quality should be a little higher. ![image](https://private-user-images.githubusercontent.com/1161586/357207813-29d6925b-f5a9-4556-a834-267d0b67033c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTkxMTYsIm5iZiI6MTcyMzQ5ODgxNiwicGF0aCI6Ii8xMTYxNTg2LzM1NzIwNzgxMy0yOWQ2OTI1Yi1mNWE5LTQ1NTYtYTgzNC0yNjdkMGI2NzAzM2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMjE0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY1NjAwN2NlZWU4NjAyZTY4NmQ0MmVkYWJiZjBkYjkwYzA2OGVkMjhlNTU0MjAwNGMxM2E4ZDkzM2Q2NjdjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WpdCpP-BUFjcy6WhgQj2sxJFtvbuIGAZBYDADedwV8U)

I think it's fairly reasonable considering that it's only for visualization. But yeah, we should test on some different environments first.

2024-08-12 21:52 UTC, calvertdw approved these changes

2024-08-12 21:56 UTC, calvertdw commented
> > Seeing this, it looks a little choppy. Would be better to see it on real robot data, however, I think the quality should be a little higher. ![image](https://private-user-images.githubusercontent.com/1161586/357207813-29d6925b-f5a9-4556-a834-267d0b67033c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTkxMTYsIm5iZiI6MTcyMzQ5ODgxNiwicGF0aCI6Ii8xMTYxNTg2LzM1NzIwNzgxMy0yOWQ2OTI1Yi1mNWE5LTQ1NTYtYTgzNC0yNjdkMGI2NzAzM2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMjE0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY1NjAwN2NlZWU4NjAyZTY4NmQ0MmVkYWJiZjBkYjkwYzA2OGVkMjhlNTU0MjAwNGMxM2E4ZDkzM2Q2NjdjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WpdCpP-BUFjcy6WhgQj2sxJFtvbuIGAZBYDADedwV8U)
> 
> I think it's fairly reasonable considering that it's only for visualization. But yeah, we should test on some different environments first.

It's one thing for us to see the data, but screenshots and video recordings of our UI also represent our organization. I'd like us to look good in that respect, too. So just under the obvious level of degradation would be nice. Additionally, I think sometimes people would get confused and think the sensor sucks, and subliminally make assumptions going forward. I remember myself doing that a lot early on.

2024-08-12 22:23 UTC, TomaszTB commented
> I think we should change the topics in this PR so it's like:
> 
> ```
> /ihmc/d455/image/depth/compressed
> ```
> 
> That way it's clear you probably shouldn't run perception algorithms on it.

Unfortunately the suffix is already taken by the "depth" part. Not sure how we can add more after the suffix. 

Can we make that a separate PR? I feel like it doesn't relate to nvCOMP and using a different depth compression method.

2024-08-12 22:24 UTC, ds58 commented
> > I think we should change the topics in this PR so it's like:
> > ```
> > /ihmc/d455/image/depth/compressed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That way it's clear you probably shouldn't run perception algorithms on it.
> 
> Unfortunately the suffix is already taken by the "depth" part. Not sure how we can add more after the suffix.
> 
> Can we make that a separate PR? I feel like it doesn't relate to nvCOMP and using a different depth compression method.

What if we use `/lossy` instead of `/compressed`? We are changing that aspect where it used to be lossless and now it is lossy.

2024-08-12 22:31 UTC, TomaszTB commented
> > > I think we should change the topics in this PR so it's like:
> > > ```
> > > /ihmc/d455/image/depth/compressed
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > That way it's clear you probably shouldn't run perception algorithms on it.
> > 
> > 
> > Unfortunately the suffix is already taken by the "depth" part. Not sure how we can add more after the suffix.
> > Can we make that a separate PR? I feel like it doesn't relate to nvCOMP and using a different depth compression method.
> 
> What if we use `/lossy` instead of `/compressed`? We are changing that aspect where it used to be lossless and now it is lossy.

Ah, that does relate more. Still will have to figure out how to add the "lossy" into there.

2024-08-12 22:35 UTC, TomaszTB commented
> > > Seeing this, it looks a little choppy. Would be better to see it on real robot data, however, I think the quality should be a little higher. ![image](https://private-user-images.githubusercontent.com/1161586/357207813-29d6925b-f5a9-4556-a834-267d0b67033c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTkxMTYsIm5iZiI6MTcyMzQ5ODgxNiwicGF0aCI6Ii8xMTYxNTg2LzM1NzIwNzgxMy0yOWQ2OTI1Yi1mNWE5LTQ1NTYtYTgzNC0yNjdkMGI2NzAzM2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMjE0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY1NjAwN2NlZWU4NjAyZTY4NmQ0MmVkYWJiZjBkYjkwYzA2OGVkMjhlNTU0MjAwNGMxM2E4ZDkzM2Q2NjdjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WpdCpP-BUFjcy6WhgQj2sxJFtvbuIGAZBYDADedwV8U)
> > 
> > 
> > I think it's fairly reasonable considering that it's only for visualization. But yeah, we should test on some different environments first.
> 
> It's one thing for us to see the data, but screenshots and video recordings of our UI also represent our organization. I'd like us to look good in that respect, too. So just under the obvious level of degradation would be nice. Additionally, I think sometimes people would get confused and think the sensor sucks, and subliminally make assumptions going forward. I remember myself doing that a lot early on.
> 
> There's also the fact that through, interdependence, visualization of data is actionable in our UI, through teleoperation and behavior authoring. So in that respect, the operator is a "perception algorithm".

I added a link to 75 quality. I think there's minor improvement above 75. Also, the images I included are quite zoomed in. I'll try to get a video in the lab so we can see what it looks like in normal use.

2024-08-14 19:24 UTC, ds58 approved these changes

2024-08-14 20:28 UTC, merged