Video Streaming
ihmcrobotics/ihmc-open-robotics-software pull request #366
Opened 2024-09-23 15:10 UTC by TomaszTB

This is WIP!!!

Add video streaming to reduce network usage of sending image messages.

2024-09-23 15:16 UTC, TomaszTB commented on ihmc-high-level-behaviors/src/libgdx/java/us/ihmc/rdx/logging/FFMPEGTools.java
Moved this guy to a new FFMPEG package in `ihmc-perception`. Perhaps a few other FFMPEG classes should follow?

2024-09-23 15:16 UTC, TomaszTB commented on ihmc-perception/src/main/java/us/ihmc/perception/ffmpeg/FFMPEGWebcamEncodingDemo.java
I made a lot of demos during development to make sure things work. I'm willing to delete a bunch of them if it's excessive. Just let me know how many to leave.

2024-09-23 15:34 UTC, ds58 requested changes

2024-09-23 15:34 UTC, ds58 commented on ihmc-communication/src/main/java/us/ihmc/communication/PerceptionAPI.java
> +   public static final ROS2Topic<SRTStreamStatus> ZED_DEPTH_STREAM = ZED_STREAM_STATUS.withSuffix("depth");
Can you prefix these with SRT_ ie `SRT_STREAM_STATUS`, `SRT_REALSENSE_STREAM_STATUS`, etc

2024-09-23 15:37 UTC, ds58 commented on ihmc-perception/src/main/resources/us/ihmc/perception/ffmpeg/example.webm
Need to make sure this is in LFS

2024-09-23 21:18 UTC, TomaszTB commented on ihmc-communication/src/main/java/us/ihmc/communication/PerceptionAPI.java
> +   public static final ROS2Topic<SRTStreamStatus> ZED_DEPTH_STREAM = ZED_STREAM_STATUS.withSuffix("depth");
Done!

2024-10-09 18:23 UTC, calvertdw commented on ihmc-communication/src/main/java/us/ihmc/communication/PerceptionAPI.java
> +   public static final ROS2Topic<SRTStreamStatus> SRT_REALSENSE_DEPTH_STREAM_STATUS = SRT_REALSENSE_STREAM_STATUS.withSuffix("depth");
Can you condense these into a reduced set of topics? I'd assume color and depth status could be communicated in the base status message/topic. This simplifies a lot of things, including reducing state inconsistency and threading errors.

2024-10-09 19:25 UTC, TomaszTB commented on ihmc-communication/src/main/java/us/ihmc/communication/PerceptionAPI.java
> +   public static final ROS2Topic<SRTStreamStatus> SRT_REALSENSE_DEPTH_STREAM_STATUS = SRT_REALSENSE_STREAM_STATUS.withSuffix("depth");
I'm not sure how I'd go about doing that. Do you have any immediate ideas?

2024-10-15 19:56 UTC, ds58 approved these changes

2024-10-17 16:07 UTC, merged

2024-10-23 17:58 UTC, calvertdw commented on ihmc-communication/src/main/java/us/ihmc/communication/packets/MessageTools.java
> +   public static <T extends Packet<T>> ByteBuffer serialize(T message)
Looks like these guys allocate and copy memory. Is that a performance penalty?

2024-10-23 17:58 UTC, calvertdw commented on ihmc-communication/src/main/java/us/ihmc/communication/PerceptionAPI.java
> +   public static final ROS2Topic<SRTStreamStatus> SRT_REALSENSE_DEPTH_STREAM_STATUS = SRT_REALSENSE_STREAM_STATUS.withSuffix("depth");
Nope we talked about this and I think it's good :+1: