Switch CRDT Synchronization Algorithm to Latest Modification
ihmcrobotics/ihmc-open-robotics-software pull request #548
Opened 2024-12-17 23:44 UTC by calvertdw

TODO:
Check JSON sanitizer

2025-01-06 19:30 UTC, calvertdw commented on ihmc-communication/src/main/java/us/ihmc/communication/AutonomyAPI.java
> +                                                                             .withQoS(ROS2QosProfile.RELIABLE());
Switched to RELIABLE, which should avoid dropped messages and resulting errors, even though we handle those and it won't break if they are.

2025-01-06 19:31 UTC, calvertdw commented on ihmc-communication/src/main/java/us/ihmc/communication/crdt/CRDTBidirectionalBoolean.java
> +   private final LatestTimestampModifiable latestTimestampModifiable;
Switched the implementation for all behavior code from RequestConfirmFreezable to the new LatestTimestampModifiable. The scene graph still uses RequestConfirmFreezable.

2025-01-06 19:32 UTC, calvertdw commented on ihmc-communication/src/main/java/us/ihmc/communication/crdt/CRDTBidirectionalDouble.java
> +         latestTimestampModifiable.modify();
The "freeze" verb is now "modify".

2025-01-06 19:33 UTC, calvertdw commented on ihmc-communication/src/main/java/us/ihmc/communication/crdt/CRDTInfo.java
CRDTInfo is shared between the old and new implementations. (i.e. scene graph & behaviors)

2025-01-06 19:34 UTC, calvertdw commented on ihmc-communication/src/main/java/us/ihmc/communication/crdt/LatestTimestampModifiable.java
The main new implementation.

2025-01-06 19:41 UTC, calvertdw commented on ihmc-communication/src/main/java/us/ihmc/communication/crdt/LatestModificationCRDTAlgorithm.java
Removed old experimental implementation

2025-01-06 19:41 UTC, calvertdw commented on ihmc-communication/src/main/java/us/ihmc/communication/crdt/LatestModificationReplicate.java
Removed old experimental implementation

2025-01-06 22:10 UTC, calvertdw commented on ihmc-high-level-behaviors/src/libgdx/java/us/ihmc/rdx/ui/behavior/tree/RDXAvailableBehaviorTreeDirectory.java
> +   private final RDXBehaviorTree behaviorTree;
Make naming more consistent with other classes

2025-01-06 22:11 UTC, calvertdw commented on ihmc-high-level-behaviors/src/libgdx/java/us/ihmc/rdx/ui/behavior/tree/RDXBehaviorTree.java
> +public class RDXBehaviorTree extends BehaviorTree<RDXBehaviorTreeNode<?, ?>>
Extracted executor & RDX common logic into BehaviorTree

2025-01-06 22:12 UTC, calvertdw commented on ihmc-high-level-behaviors/src/libgdx/java/us/ihmc/rdx/ui/behavior/tree/RDXBehaviorTreeNode.java
> +      implements BehaviorTreeNodeHighLayer<RDXBehaviorTreeNode<?, ?>, S, D>
BehaviorTreeNodeLayer reworked into a new BehaviorTreeNodeHighLayer class (see later comment)

2025-01-06 22:15 UTC, calvertdw commented on ihmc-high-level-behaviors/src/libgdx/java/us/ihmc/rdx/ui/behavior/tree/RDXBehaviorTreeNodeCreationMenu.java
> +   private final BehaviorTreeTopologyOperationQueue<RDXBehaviorTreeNode<?, ?>> topologyOperationQueue;
Parameterizing this class allowed to make more things compile errors instead of runtime errors, and extract more common logic

2025-01-06 22:16 UTC, calvertdw commented on ihmc-high-level-behaviors/src/libgdx/java/us/ihmc/rdx/ui/behavior/tree/RDXBehaviorTreeWidgetsVerticalLayout.java
> +               topologyOperationQueue.queueDestroySubtreeModify(node);
Simpler and clearer here

2025-01-06 22:17 UTC, calvertdw commented on ihmc-high-level-behaviors/src/libgdx/java/us/ihmc/rdx/ui/behavior/tree/RDXROS2BehaviorTree.java
> +         ros2BehaviorTree.updateSubscription();
Important change, publication and subscription handling both happen before the update, which helps avoid edge cases and simplifies CRDT logic.

2025-01-06 22:19 UTC, calvertdw commented on ihmc-high-level-behaviors/src/libgdx/java/us/ihmc/rdx/ui/behavior/tree/RDXROS2BehaviorTree.java
> +                                  ros2BehaviorTree.getBehaviorTreeSubscription().getOutOfOrderCount()));
![image](https://github.com/user-attachments/assets/50ae32ac-78a5-454a-a3f8-05849828cfec)

2025-01-06 22:20 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTree.java
Extracted common code between RDXBehaviorTree and BehaviorTreeExecutor, made possible with the new BehaviorTreeNodeHighLayer class (see later comment).

2025-01-06 22:21 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTree.java
> +   private final LatestTimestampModifiable dataModification;
data & root reference are now separate modifiable CRDT fields. That way the topology is synced separately from the data contained by the tree and nodes.

2025-01-06 22:21 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeDefinitionRegistry.java
> +   private static final Map<Class<?>, RegistryRecord> recordMap = new HashMap<>();
Added a map to provide a few useful methods.

2025-01-06 22:23 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeNode.java
> +public interface BehaviorTreeNode<LT extends BehaviorTreeNode<LT>>
Was thinking about this T wrong before. Documented it to not forget.

2025-01-06 22:24 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeNodeDefinition.java
> +      childrenModification = new LatestTimestampModifiable(crdtInfo);
The data modifiable is extended, but the children are kept as a separate modifiable in order to handle topology synchronization separately from data, to improve understandability in the ROS2BehaviorTreeSubscription class.

2025-01-06 22:24 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeNodeDefinition.java
> +      childrenModification.setModifierName(crdtInfo.getActorDesignation().name() + ": " + name.getValue() + " children");
These greatly help with debugging, which need to be left in so we can debug any issues going forward.

2025-01-06 22:27 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeNodeHighLayer.java
This class was a bit of an "ah ha" moment. The old BehaviorNodeLayer class would also represent the state layer, which did not help anything and only made things more complicated. Now this interface only represents RDX & Executor layers, which makes it a lot more useful for extracting common logic, as the state implementations are shared anyway.

2025-01-06 22:45 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/ros2/ROS2BehaviorTree.java
> -@SuppressWarnings({"rawtypes", "unchecked"})
No longer have warning with the new parameterizations!

2025-01-06 22:47 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/ros2/ROS2BehaviorTreeMessageTools.java
> +      treeStateMessage.getPartialDataNodes().clear();
Partial data is now stored separately in the state messages, no longer exploiting the basic nodes field which was confusing.

2025-01-06 22:47 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/ros2/ROS2BehaviorTreeMessageTools.java
> -      else if (subscriptionNode.getType() == AI2RNodeDefinition.class && nodeState instanceof AI2RNodeState ai2rNodeState)
Was able to remove this bit of boilerplate

2025-01-06 22:48 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/ros2/ROS2BehaviorTreeSubscription.java
> -@SuppressWarnings({"unchecked"}) // Sometimes in this class we need to be a little unsafe
No more warnings :D

2025-01-06 22:53 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/ros2/ROS2BehaviorTreeSubscription.java
Major modifications to the subscription implementation.

2025-01-06 22:54 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/topology/BehaviorTreeNodeInsertionDefinition.java
Rewrote/simplified this a lot.

2025-01-06 22:55 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/topology/BehaviorTreeTopologyOperationQueue.java
Rewrote the topology operations almost entirely. Hopefully you'd agree it's more readable and concise now.

2025-01-06 22:56 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/topology/BehaviorTreeTopologyOperations.java
Rewrote the topology operations almost entirely. Hopefully you'd agree it's more readable and concise now.

2025-01-06 22:57 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/sequence/ActionNodeInitialization.java
> -         handPoseAction.getState().update();
A lot of getState() methods went away because it's already a state

2025-01-06 22:58 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/sequence/actions/FootstepPlanActionExecutor.java
> +            state.copyDefinitionToGoalFootstepToGoalTransform(side);
Foostep -> Footstep

2025-01-06 22:58 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/sequence/actions/FootstepPlanActionPlanningThread.java
> +      FootstepPlan footstepPlan = footstepPlannerOutput == null ? new FootstepPlan() : footstepPlannerOutput.getFootstepPlan();
Fix NPE bug

2025-01-06 23:00 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/trashCan/TrashCanInteractionState.java
> +      super.fromMessage(message.getState());
State fromMessage needs to happen after definition fromMessage. This was a mistake which reared it's head in the new implementation.

2025-01-06 23:01 UTC, calvertdw commented on ihmc-interfaces/src/main/messages/ihmc_interfaces/behavior_msgs/msg/BehaviorTreeNodeDefinitionMessage.msg
Storing the type of node so we can use it and know it in the case of partial data being sent. Also separating the children modification from data modification.

2025-01-06 23:02 UTC, calvertdw commented on ihmc-interfaces/src/main/messages/ihmc_interfaces/behavior_msgs/msg/BehaviorTreeStateMessage.msg
> +byte PARTIAL_DATA = 0
Partial data is now code 0

2025-01-06 23:02 UTC, calvertdw commented on ihmc-interfaces/src/main/messages/ihmc_interfaces/behavior_msgs/msg/BehaviorTreeStateMessage.msg
> +behavior_msgs/BasicNodeStateMessage[<=500] partial_data_nodes
Good to have the limit at 500 since that's going to determine our max tree size.

2025-01-06 23:02 UTC, calvertdw commented on ihmc-interfaces/src/main/messages/ihmc_interfaces/ihmc_common_msgs/msg/LatestModificationMessage.msg
Message used for CRDT

2025-01-06 23:03 UTC, calvertdw commented on ihmc-robotics-toolkit/src/main/java/us/ihmc/robotics/referenceFrames/DetachableReferenceFrame.java
> +      return referenceFrame != null && referenceFrame.getRootFrame() == ReferenceFrame.getWorldFrame();
Fix NPE

2025-01-07 18:33 UTC, ds58 requested changes

2025-01-07 18:33 UTC, ds58 commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeNodeHighLayer.java
> +public interface BehaviorTreeNodeHighLayer<HLT extends BehaviorTreeNodeHighLayer<HLT, ?, ?>,
I dont like the term "layer" or "high layer", I think we should remove that from everywhere in the behavior tree. Can this be called `BehaviorTreeNodeInstance``? As in this thing is _usable_ instance of BehaviorTreeNode which has a state and can be updated

2025-01-08 16:25 UTC, TomaszTB reviewed
Few minor things

2025-01-08 16:25 UTC, TomaszTB commented on ihmc-communication/src/main/java/us/ihmc/communication/crdt/LatestTimestampModifiable.java
> +   public void setModifierName(String ourName)
Everywhere this is used it has`crdtInfo.getActorDesignation().name() + ": " + name`. Maybe the crdtInfo part can be added within the method so it's there by default? Would there ever be a case where we don't want the crdtInfo part?

2025-01-08 16:25 UTC, TomaszTB commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTree.java
> +    * Use to safefly modify the tree, ensuring it's updated afterwards.
Typo
```suggestion
    * Use to safely modify the tree, ensuring it's updated afterwards.
```

2025-01-08 16:25 UTC, TomaszTB commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeDefinitionRegistry.java
> +   private static final Map<Class<?>, RegistryRecord> recordMap = new HashMap<>();
Maybe call it `DEFINITIONS_MAP` to make it more clear that it's a map containing the `DEFINITIONS`?

2025-01-08 16:25 UTC, TomaszTB commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeNodeHighLayer.java
> +public interface BehaviorTreeNodeHighLayer<HLT extends BehaviorTreeNodeHighLayer<HLT, ?, ?>,
I agree "layer" is weird. When I first read the name I thought the class represented a layer of nodes within the tree (like a list of node that are at the same depth).

2025-01-08 16:25 UTC, TomaszTB commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/ros2/ROS2BehaviorTreeSubscription.java
> +   private final Consumer<HLT> rootNodeSetter;
This rootNodeSetter isn't used. Could it be removed?

2025-01-08 16:25 UTC, TomaszTB commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/ros2/ROS2BehaviorTreeSubscription.java
> +import us.ihmc.behaviors.behaviorTree.BehaviorTreeDefinitionRegistry;
This import isn't used
```suggestion
```

2025-01-08 16:25 UTC, TomaszTB commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/topology/BehaviorTreeTopologyOperations.java
> + * The {@code *Modify} methods mark any node who's children gets changed's children field as modified
I'm struggling to understand what this line is saying... is it saying this?
> The `*Modify` methods mark any node whose children have been modified as modified

2025-01-08 22:07 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeNodeHighLayer.java
> +public interface BehaviorTreeNodeHighLayer<HLT extends BehaviorTreeNodeHighLayer<HLT, ?, ?>,
These are abstraction "layers". We need a word for them (BehaviorTreeNodeInstance is ambiguous, that is already the BehaviorTreeNode interface).

There are 3 "layers" currently:
- High "layer": RDX & Executor implementations
- State "layer"
- Definition "layer"

What can we replace the word "layer" with?

2025-01-08 23:16 UTC, TomaszTB commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeNodeHighLayer.java
> +public interface BehaviorTreeNodeHighLayer<HLT extends BehaviorTreeNodeHighLayer<HLT, ?, ?>,
To me it seems like this "high layer" is the embodiment of a "BehaviorTreeNode" since it has both definition and state, while the current `BehaviorTreeNode` only provides access to the parent and children. How about this: 
* `BehaviorTreeNode` -> `BehaviorTreeNodeInterface`
* `BehaviorTreeNodeHighLayer` -> `BehaviorTreeNode`

I'm not a huge fan of putting "Interface" in any class name, but I think it makes sense in this case.

2025-01-09 21:04 UTC, ds58 commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeNodeHighLayer.java
> +public interface BehaviorTreeNodeHighLayer<HLT extends BehaviorTreeNodeHighLayer<HLT, ?, ?>,
I like @TomaszTB suggestion, however is it possible there is a better name for `BehaviorTreeNodeInterface`?

2025-01-09 21:34 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeDefinitionRegistry.java
> +   private static final Map<Class<?>, RegistryRecord> recordMap = new HashMap<>();
Done!

2025-01-09 21:38 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeNodeHighLayer.java
> +public interface BehaviorTreeNodeHighLayer<HLT extends BehaviorTreeNodeHighLayer<HLT, ?, ?>,
The terms interface and instance both feel too ambiguous to use here...

2025-01-09 22:04 UTC, calvertdw commented on ihmc-communication/src/main/java/us/ihmc/communication/crdt/LatestTimestampModifiable.java
> +   public void setModifierName(String ourName)
Done, thanks!

2025-01-09 22:05 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTree.java
> +    * Use to safefly modify the tree, ensuring it's updated afterwards.
Fixed, thanks!

2025-01-09 22:08 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/ros2/ROS2BehaviorTreeSubscription.java
> +   private final Consumer<HLT> rootNodeSetter;
Very thorough review, thanks! Fixed.

2025-01-09 22:09 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/ros2/ROS2BehaviorTreeSubscription.java
> +import us.ihmc.behaviors.behaviorTree.BehaviorTreeDefinitionRegistry;
Fixed!

2025-01-09 22:13 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/topology/BehaviorTreeTopologyOperations.java
> + * The {@code *Modify} methods mark any node who's children gets changed's children field as modified
I have updated it
> Static topological behavior tree operations to keep the logic in one place.
The {@code *Modify} methods are for the purpose of CRDT synchronization.
When a user or automated algorithm initiates a modification to the tree topology
(i.e. changing the set of children), then we mark the children field as modified
through the associated LatestTimestampModifiable.
The methods without {@code *Modify} would be exclusively operations as a result
of getting in sync with the changes that happened on other networked peers.

2025-01-09 22:46 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/BehaviorTreeNodeHighLayer.java
> +public interface BehaviorTreeNodeHighLayer<HLT extends BehaviorTreeNodeHighLayer<HLT, ?, ?>,
Done! We went with BehaviorTreeNodeHighLayer -> BehaviorTreeNode to properly glorify it, and simplify the name of BehaviorTreeNode -> TreeNode, since it is just holding parent & children and nothing specific to behaviors.

2025-01-10 14:54 UTC, TomaszTB approved these changes
:tada:

2025-01-10 17:29 UTC, ds58 requested changes
Can you rename all generic type `<LT>` and `<HLT>` since that name doesn't mean anything anymore?

2025-01-10 17:29 UTC, ds58 commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/TreeNode.java
> + * @param <LT> The generic type of this node layer: UI, Executor, State, or Definition
Rename `<LT>` and remove reference to UI, Executor, State, or Definition, since this is not a specific thing for behaviors

2025-01-13 20:21 UTC, ds58 approved these changes

2025-01-13 21:16 UTC, calvertdw commented on ihmc-high-level-behaviors/src/main/java/us/ihmc/behaviors/behaviorTree/TreeNode.java
> + * @param <LT> The generic type of this node layer: UI, Executor, State, or Definition
Done

2025-01-14 00:36 UTC, merged